-- Urban Review System - Base review_requests table for Supabase
-- Safe to run once before the hardening migration.

CREATE TABLE IF NOT EXISTS public.review_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_name text,
  client_email text,
  client_phone text,
  event_type text NOT NULL,
  channel text NOT NULL DEFAULT 'email',
  unique_token text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'request_pending',
  office_code text,
  rating integer,
  feedback text,
  internal_feedback text,
  notes text,
  comment text,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  request_sent_at timestamptz,
  first_reminder_sent_at timestamptz,
  second_reminder_sent_at timestamptz,
  last_reminder_at timestamptz,
  review_submitted_at timestamptz,
  feedback_submitted_at timestamptz,
  last_channel_status text,
  last_channel_detail text,
  last_channel_provider text,
  last_channel_message_id text,
  external_source text,
  external_event_id text
);

CREATE INDEX IF NOT EXISTS idx_review_requests_unique_token
  ON public.review_requests (unique_token);

CREATE INDEX IF NOT EXISTS idx_review_requests_status
  ON public.review_requests (status);

CREATE INDEX IF NOT EXISTS idx_review_requests_created_at
  ON public.review_requests (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_review_requests_office_code
  ON public.review_requests (office_code);

CREATE INDEX IF NOT EXISTS idx_review_requests_external_event
  ON public.review_requests (external_source, external_event_id);

CREATE INDEX IF NOT EXISTS idx_review_requests_status_created_at
  ON public.review_requests (status, created_at DESC);
